
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ASSIGN BOOL COLON COLONEQ COMMA DIFFERENT DIVIDE DMINUS DPLUS ELSE EQUALS FALSE FOR FUNC GREATER GREATER_EQUAL ID IF IMPORT INT LCHAVES LESS LESS_EQUAL LPAREN MINUS MOD NUMBER OR PACKAGE PLUS RANGE RCHAVES RETURN RPAREN SEMICOLON STRING STRUCT TIMES TRUE TYPE VARexp : exp1exp1 : exp2exp2 : NUMBERexp : exp PLUS exp1exp : exp MINUS exp1 exp1 : exp1 TIMES exp2exp1 : exp1 DIVIDE exp2'
    
_lr_action_items = {'NUMBER':([0,5,6,7,8,],[4,4,4,4,4,]),'$end':([1,2,3,4,9,10,11,12,],[0,-1,-2,-3,-4,-5,-6,-7,]),'PLUS':([1,2,3,4,9,10,11,12,],[5,-1,-2,-3,-4,-5,-6,-7,]),'MINUS':([1,2,3,4,9,10,11,12,],[6,-1,-2,-3,-4,-5,-6,-7,]),'TIMES':([2,3,4,9,10,11,12,],[7,-2,-3,7,7,-6,-7,]),'DIVIDE':([2,3,4,9,10,11,12,],[8,-2,-3,8,8,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,],[1,]),'exp1':([0,5,6,],[2,9,10,]),'exp2':([0,5,6,7,8,],[3,3,3,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> exp1','exp',1,'p_exp_exp1','parser.py',10),
  ('exp1 -> exp2','exp1',1,'p_exp2','parser.py',14),
  ('exp2 -> NUMBER','exp2',1,'p_exp3','parser.py',18),
  ('exp -> exp PLUS exp1','exp',3,'p_exp_plus','parser.py',22),
  ('exp -> exp MINUS exp1','exp',3,'p_exp_minus','parser.py',26),
  ('exp1 -> exp1 TIMES exp2','exp1',3,'p_exp_times','parser.py',30),
  ('exp1 -> exp1 DIVIDE exp2','exp1',3,'p_exp_divide','parser.py',34),
]
